### ISSUE TITLE
怎么实现点击查看大图的

### ISSUE THREAD

**Issue by sundjly** [loadingwyn/react-imageslides#1]
点击图片的时候把url传给了组件ImageSlides的images，但是没有显示图片，一直显示加载，请问是什么原因

**Comment by loadingwyn** [comment]
是不是网络问题？只有图片加载出来才会显示

**Comment by loadingwyn** [comment]
https://codesandbox.io/s/l2xpwy3xrq?view=preview 你可以在这里试下
