### ISSUE TITLE
Prop index unable to present the right images

### ISSUE THREAD

**Issue by georgezhang** [loadingwyn/react-imageslides#17]
The prop "index" is not accurate to present the current image of index. You can reproduce the issue on the demo https://codesandbox.io/s/l2xpwy3xrq?view=preview&file=/index.js:698-707 . After changed index from {0} to {1}, the image didn't change. I guess the problem is on the method getMedianIndex() in ImageSlides. Please fix.

**Comment by easteryard** [comment]
I'm having the same problem. It shows the previous image of the index you pass to the `index` prop.
