### ISSUE TITLE
Zoom in/out when image slider displayed on the web

### ISSUE THREAD

**Issue by kostebudinoski** [loadingwyn/react-imageslides#6]
Is there a possibility to zoom in/out the images when slider is rendered on the web browser Would it be possible to add this feature, for example when doubled clicked the image on specific position or with mouse scroll in/out to zoom in/out the image?

Thanks for the great library!

**Comment by loadingwyn** [comment]
You mean supporting desktop browser ?

**Comment by kostebudinoski** [comment]
Correct, supporting desktop browser.

**Comment by loadingwyn** [comment]
I'll do it.

**Comment by loadingwyn** [comment]
@kostebudinoski You can try v1.3.0  now

**Comment by kostebudinoski** [comment]
Cool, looks great! Thank you!
